
[2022-04-04 13:23:56,296.296]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111
[2022-04-04 13:23:56,297.297]	 ERROR [	app.log_exception:1457]	 Exception on /indexcliente/ [POST]
Traceback (most recent call last):
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jesus\PycharmProjects\tareaTema3Project\app\private\routes.py", line 27, in indexcliente
    if cliente.dni == formFiltro.dni.data:
AttributeError: 'BaseQuery' object has no attribute 'dni'
[2022-04-04 13:24:17,661.661]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111y
[2022-04-04 13:24:17,661.661]	 ERROR [	app.log_exception:1457]	 Exception on /indexcliente/ [POST]
Traceback (most recent call last):
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jesus\PycharmProjects\tareaTema3Project\app\private\routes.py", line 27, in indexcliente
    if cliente.dni == formFiltro.dni.data:
AttributeError: 'BaseQuery' object has no attribute 'dni'
[2022-04-04 13:26:18,735.735]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111y
[2022-04-04 13:32:43,665.665]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111
[2022-04-04 13:32:43,665.665]	 ERROR [	app.log_exception:1457]	 Exception on /indexcliente/ [POST]
Traceback (most recent call last):
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jesus\PycharmProjects\tareaTema3Project\app\private\routes.py", line 27, in indexcliente
    dni = cliente.dni
AttributeError: 'BaseQuery' object has no attribute 'dni'
[2022-04-04 13:34:47,673.673]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111
[2022-04-04 13:35:33,068.68]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111
[2022-04-04 13:39:29,328.328]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111
[2022-04-04 13:39:29,329.329]	 ERROR [	app.log_exception:1457]	 Exception on /indexcliente/ [POST]
Traceback (most recent call last):
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jesus\PycharmProjects\tareaTema3Project\app\private\routes.py", line 27, in indexcliente
    if cliente.dni:
AttributeError: 'BaseQuery' object has no attribute 'dni'
[2022-04-04 13:39:56,922.922]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111
[2022-04-04 13:39:56,922.922]	 ERROR [	app.log_exception:1457]	 Exception on /indexcliente/ [POST]
Traceback (most recent call last):
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jesus\PycharmProjects\tareaTema3Project\app\private\routes.py", line 27, in indexcliente
    if cliente.dni == formFiltro.dni.data:
AttributeError: 'BaseQuery' object has no attribute 'dni'
[2022-04-04 13:40:31,022.22]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111y
[2022-04-04 13:40:31,023.23]	 ERROR [	app.log_exception:1457]	 Exception on /indexcliente/ [POST]
Traceback (most recent call last):
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jesus\PycharmProjects\tema3FlaskProject\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\jesus\PycharmProjects\tareaTema3Project\app\private\routes.py", line 27, in indexcliente
    if cliente.dni == formFiltro.dni.data:
AttributeError: 'BaseQuery' object has no attribute 'dni'
[2022-04-04 13:44:32,982.982]	 INFO [	app.indexcliente:24]	 Se busca cliente con DNI: 111111111y
[2022-04-04 13:44:32,983.983]	 INFO [	app.indexcliente:28]	 Se encuentra cliente con DNI: 111111111y
